[package]
name = "metasearch-parsers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lol_html.workspace = true
quick-xml.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true
