[package]
name = "metasearch-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
futures-util.workspace = true
indexmap.workspace = true
js-sys.workspace = true
metasearch-core = { path = "../metasearch-core" }
url.workspace = true
wasm-bindgen.workspace = true
web-bot-auth.workspace = true
worker.workspace = true
uuid.workspace = true
